#!/usr/bin/php -q
<?php

if (php_sapi_name() != "cli") { 
	err($fa.$argv[0]." must be run in the command line.");
	exit(1);
}
$exe = array_shift($argv); // remove filename

if (!$fname = array_shift($argv)) {
	exit("Usage: ".$exe." input-file\n");
}

try {
	if (class_exists('Phar',false)) {
		Phar::mapPhar('lessify.phar');
		require "phar://lessify.phar/lessify.inc.php";
	}
} catch (Exception $ex) {}

if (!class_exists('lessify',false)) {
	$path  = realpath(dirname(__FILE__)).'/';

	require $path."lessify.inc.php";
}

try  {
	$parser = new lessify($fname);
	echo $parser->parse();
} catch (exception $e) {
	exit("Fatal error: ".$e->getMessage()."\n");
}

__HALT_COMPILER(); ?>
