#!/usr/bin/php
<?php


require_once "less.lex.php";

array_shift($argv);
$name = array_pop($argv);

if (!$name) exit("./parse [options] file-name\n");

function has($flag) {
	global $argv;
	foreach ($argv as $a) {
		if ("-".$flag == $a) return true;
	}
	return false;
}


$lex = less_lex::from_file($name);
$tokens = array();
while (($token = $lex->next_token()) != $lex::EOF) {
	$tokens[] = $token;
	if ($token[0] != "white") {
		// echo $lex->format_token($token)."\n";
	}
}
// echo PHP_EOL;

$p = new less_parse();
$tree = $p->parse($tokens);

if (has("X")) {
	print_r($tree);
} else {
	$less = new lessc();
	echo $less->compile($p->link_block($tree));
}

